---
name: Hello

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu_latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Say "Hi!"
        shell: bash
        working-directory: build
        run: |
          echo "Hi!"
